[
uuid(3f299c8f-35db-46b2-9def-6a49e339f6ff),
version(1.0)
]
interface ShadowDriverRPC
{
	void RPCTest([in, string] unsigned char* pszString);
	void GetShadowDriverVersion(void);
	void Shutdown(void);
}

